@start=2023-07-01T11:32:51Z
@end=2023-07-31T20:42:51Z
@category1=Zoomba
@session-host = http://localhost:5157
@gymId = 

GET {{session-host}}/gyms/{{gymId}}/sessions?startDateTime={{start}}&endDateTime={{end}}&categories={{category1}}

### no date time
GET {{session-host}}/gyms/{{gymId}}/sessions?categories={{category1}}

### no categories
GET {{session-host}}/gyms/{{gymId}}/sessions?startDateTime={{start}}&endDateTime={{end}}

### no categories or date time
GET {{session-host}}/gyms/{{gymId}}/sessions