@gym-host = http://localhost:5218
@adminId = 95d5cd2b-cb0a-4aca-87f7-94728b042a7b

POST {{gym-host}}/subscriptions
Content-Type: application/json

{
  "SubscriptionType": "Starter",
  "AdminId": "{{adminId}}"
}